/**
 * Thin marketplace-factory seeds. Same ENTITY + OFFER/SEEK + attributes.
 * No vertical types. Travel reuses listing/seeker. Scale: 2026-verticals.
 */
const CREATED = "2026-09-13T02:00:00.000Z";
const DC = { city: "Washington", region: "DC", country: "US" };
const NYC = { city: "New York", region: "NY", country: "US" };
const BERLIN = { city: "Berlin", region: "BE", country: "DE" };

type Entity = Record<string, unknown> & { id: string; type: string };

function trust(
  status: "unscored" | "stub" | "evidence",
  notes: string,
  evidence?: Record<string, unknown>,
) {
  return {
    status,
    provenance: "synthetic" as const,
    notes,
    ...(evidence ? { evidence } : {}),
  };
}

function meta(vertical: string, demoLabel: string, extra: Record<string, unknown> = {}) {
  return { demo: true, demoLabel, vertical, scale: "2026-verticals", ...extra };
}

function base(
  e: Omit<Entity, "created_at" | "capabilities" | "preferences"> & {
    capabilities?: string[];
    preferences?: Record<string, unknown>;
    created_at?: string;
  },
): Entity {
  return {
    ...e,
    capabilities: e.capabilities ?? e.offers,
    preferences: e.preferences ?? {},
    created_at: e.created_at ?? CREATED,
  };
}

const TODAY = "2026-09-13";

export function buildFactoryEntities(): Entity[] {
  return [
    ...products(),
    ...experts(),
    ...capital(),
    ...travel(),
    ...events(),
    ...childcare(),
    ...collab(),
    ...compute(),
    ...data(),
    ...local(),
    ...metaMarket(),
  ];
}

function products(): Entity[] {
  return [
    base({
      id: "eval-product-drill",
      type: "product",
      name: "Harbor 18V drill",
      description:
        "DEMO synthetic corded-look 18V drill in stock at a DC merchant. Not a real SKU. Who else sells an equivalent cheaper?",
      offers: ["drill", "18V drill", "this product", "this drill", "in stock"],
      seeks: ["buyer who needs a drill", "someone who needs a cheaper equivalent"],
      location: DC,
      attributes: {
        synthetic: true,
        role: "seller",
        kind: "drill",
        sku: "DRILL-18V-HARBOR",
        price: 40,
        currency: "USD",
        inStock: true,
        equivalentTo: "drill",
        stock: 12,
        state: "in_stock",
      },
      metadata: meta("products", "DEMO synthetic product"),
      trust: trust("stub", "synthetic product — not inventory"),
      provenance: "synthetic",
    }),
    base({
      id: "product-drill-brushless",
      type: "product",
      name: "Brushless 18V drill (cheaper equivalent)",
      description: "DEMO cheaper equivalent 18V drill in stock. Substitution proof. Not a real SKU.",
      offers: ["drill", "equivalent drill", "cheaper equivalent", "18V drill", "in stock", "substitution"],
      seeks: ["buyer who wants a cheaper drill"],
      location: DC,
      attributes: {
        synthetic: true,
        role: "seller",
        kind: "drill",
        sku: "DRILL-18V-BRUSH",
        price: 28,
        currency: "USD",
        inStock: true,
        equivalentTo: "drill",
        stock: 7,
        state: "in_stock",
      },
      metadata: meta("products", "DEMO synthetic product"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "product-drill-soldout",
      type: "product",
      name: "Pro 20V drill (sold out)",
      description: "DEMO sold-out drill — inventory state, not a shop. Not a real SKU.",
      offers: ["drill", "20V drill", "this product"],
      seeks: ["restock"],
      location: DC,
      attributes: {
        synthetic: true,
        role: "seller",
        kind: "drill",
        sku: "DRILL-20V-PRO",
        price: 89,
        currency: "USD",
        inStock: false,
        equivalentTo: "drill",
        stock: 0,
        state: "sold_out",
      },
      metadata: meta("products", "DEMO synthetic product"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "company-hardware-dc",
      type: "company",
      name: "Potomac Hardware",
      description: "DEMO synthetic DC merchant that sells drills and tools. Not a real store.",
      offers: ["sells this drill", "merchant", "in stock", "hardware"],
      seeks: ["buyers nearby"],
      location: DC,
      attributes: { synthetic: true, role: "seller", kind: "drill", price: 42, currency: "USD", inStock: true },
      metadata: meta("products", "DEMO synthetic merchant"),
      trust: trust("stub", "synthetic merchant"),
      provenance: "synthetic",
    }),
    base({
      id: "buyer-needs-drill",
      type: "human",
      name: "Chris needs a drill",
      description: "DEMO synthetic buyer looking for a cheaper equivalent 18V drill. Not a real person.",
      offers: ["cash today", "pickup in DC"],
      seeks: ["drill", "cheaper equivalent", "18V drill", "this product", "in stock"],
      location: DC,
      attributes: { synthetic: true, role: "buyer", kind: "drill", price: 35, currency: "USD", budget: 35 },
      metadata: meta("products", "DEMO synthetic buyer"),
      trust: trust("stub", "synthetic buyer"),
      provenance: "synthetic",
    }),
    base({
      id: "buyer-sofa",
      type: "human",
      name: "Alex needs a sofa",
      description: "DEMO synthetic buyer looking for a sofa. Not a real person.",
      offers: ["pickup this weekend"],
      seeks: ["sofa", "this product"],
      location: DC,
      attributes: { synthetic: true, role: "buyer", kind: "sofa", price: 400, currency: "USD" },
      metadata: meta("products", "DEMO synthetic buyer"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "product-sofa-dc",
      type: "product",
      name: "Shaw sofa (in stock)",
      description: "DEMO synthetic sofa in stock. Not a real listing.",
      offers: ["sofa", "this product", "in stock"],
      seeks: ["buyer who needs a sofa"],
      location: DC,
      attributes: {
        synthetic: true,
        role: "seller",
        kind: "sofa",
        sku: "SOFA-SHAW",
        price: 380,
        currency: "USD",
        inStock: true,
        stock: 2,
      },
      metadata: meta("products", "DEMO synthetic product"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "agent-price-compare",
      type: "agent",
      name: "PriceHop",
      description: "DEMO synthetic agent that finds cheaper equivalent products. Not a shop.",
      offers: ["cheaper equivalent", "price compare", "substitution", "this product"],
      seeks: ["product identity to compare"],
      attributes: {
        synthetic: true,
        role: "seller",
        kind: "drill",
        price: 2,
        priceUsd: 2,
        latencyMs: 400,
        apiEndpoint: "/api/agents/agent-price-compare/invoke",
        mcpEndpoint: "/api/mcp",
        authRequirements: { demo: true },
      },
      metadata: {
        ...meta("products", "DEMO synthetic agent"),
        aiDisclosure: "This is an AI agent. It is not a human.",
        isAI: true,
      },
      trust: trust("stub", "synthetic agent"),
      provenance: "ai_generated",
    }),
  ];
}

function experts(): Entity[] {
  return [
    base({
      id: "eval-expert-notary",
      type: "human",
      name: "Dana the notary",
      description: "DEMO synthetic licensed notary near DC. Authority is a license stub. Not a real notary.",
      offers: ["notary", "notary near me", "knows about notarization", "expert"],
      seeks: ["documents to notarize", "ask about notary"],
      location: DC,
      attributes: { synthetic: true, role: "expert", licensed: true, domain: "notary" },
      metadata: meta("experts", "DEMO synthetic expert"),
      trust: trust("evidence", "license stub — not a real credential", {
        verified: true,
        verifiedBy: "demo-license-stub",
        licenses: ["notary-DC-DEMO"],
      }),
      provenance: "synthetic",
    }),
    base({
      id: "expert-market-human",
      type: "human",
      name: "Mira understands this market",
      description:
        "DEMO synthetic human expert. Offers help understanding this market with provenance notes. Not a real analyst.",
      offers: [
        "help understanding this market",
        "understand this market",
        "knows about this market",
        "expert",
        "market briefing",
      ],
      seeks: ["ask about this market", "questions about this market"],
      location: DC,
      attributes: { synthetic: true, role: "expert", domain: "market" },
      metadata: meta("experts", "DEMO synthetic expert"),
      trust: trust("evidence", "portfolio stub", {
        verified: true,
        verifiedBy: "demo-stub",
        portfolio: ["https://example.invalid/mira-market"],
        outcomes: [{ label: "briefed a seed round", result: "stub" }],
      }),
      provenance: "synthetic",
    }),
    base({
      id: "expert-disagrees",
      type: "human",
      name: "Owen disagrees",
      description: "DEMO synthetic expert who disagrees with the consensus on this market. Not a real person.",
      offers: ["disagrees", "contrarian take", "knows about this market", "help understanding this market"],
      seeks: ["someone who wants a second opinion"],
      location: DC,
      attributes: { synthetic: true, role: "expert", domain: "market" },
      metadata: meta("experts", "DEMO synthetic expert"),
      trust: trust("stub", "synthetic dissent — not advice"),
      provenance: "synthetic",
    }),
    base({
      id: "ai-market-analyst",
      type: "ai",
      name: "MarketSocrates",
      description:
        "This is an AI. It is not a human. DEMO analyst that offers help understanding this market from public-looking stubs.",
      offers: ["help understanding this market", "understand this market", "knows about this market", "expert"],
      seeks: ["ask about this market"],
      attributes: { synthetic: true, role: "expert", domain: "market" },
      metadata: {
        ...meta("experts", "DEMO synthetic AI expert"),
        aiDisclosure: "This is an AI. It is not a human.",
        isAI: true,
      },
      trust: trust("stub", "AI — provenance is the model, not a person"),
      provenance: "ai_generated",
    }),
    base({
      id: "company-research-desk",
      type: "company",
      name: "Civic Research Desk",
      description: "DEMO synthetic research company that briefs this market. Not a real firm.",
      offers: ["help understanding this market", "market report", "company briefing", "understand this market"],
      seeks: ["clients who need a market briefing"],
      location: DC,
      attributes: { synthetic: true, role: "expert", domain: "market" },
      metadata: meta("experts", "DEMO synthetic company"),
      trust: trust("stub", "synthetic firm"),
      provenance: "synthetic",
    }),
    base({
      id: "asker-market",
      type: "human",
      name: "Jules wants to understand this market",
      description: "DEMO synthetic asker. Needs help understanding this market. Not a real person.",
      offers: ["attention", "a specific question"],
      seeks: ["help understanding this market", "expert", "knows about this market"],
      location: DC,
      attributes: { synthetic: true, role: "asker", domain: "market" },
      metadata: meta("experts", "DEMO synthetic asker"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "asker-notary",
      type: "human",
      name: "Needs a notary today",
      description: "DEMO synthetic person who needs a notary near me. Not real.",
      offers: ["documents ready"],
      seeks: ["notary", "notary near me", "expert"],
      location: DC,
      attributes: { synthetic: true, role: "asker", domain: "notary" },
      metadata: meta("experts", "DEMO synthetic asker"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
  ];
}

function capital(): Entity[] {
  return [
    base({
      id: "investor-seed-dc",
      type: "human",
      name: "Pat writes $250k checks",
      description: "DEMO synthetic DC seed investor. Ticket size $250k. Not a real funder.",
      offers: ["invests", "writes $250k checks", "ticket size $250k", "capital", "introduction"],
      seeks: ["founder seeking a $250k check", "seed round"],
      location: DC,
      attributes: { synthetic: true, role: "investor", ticketSize: 250000, stage: "seed", currency: "USD" },
      metadata: meta("capital", "DEMO synthetic investor"),
      trust: trust("evidence", "intro stub — not a real LP", {
        outcomes: [{ label: "seed check stub", result: "synthetic" }],
      }),
      provenance: "synthetic",
    }),
    base({
      id: "investor-berlin",
      type: "human",
      name: "Greta (Berlin seed)",
      description: "DEMO synthetic Berlin investor, $200k ticket. Geo contrast. Not real.",
      offers: ["invests", "writes checks", "capital", "ticket size"],
      seeks: ["Berlin founder", "seed round"],
      location: BERLIN,
      attributes: { synthetic: true, role: "investor", ticketSize: 200000, stage: "seed", currency: "EUR" },
      metadata: meta("capital", "DEMO synthetic investor"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "company-fund-dc",
      type: "company",
      name: "Anacostia Seed",
      description: "DEMO synthetic fund that invests $250k in DC. Not a real fund.",
      offers: ["invests", "writes $250k checks", "capital", "introduction to an investor"],
      seeks: ["founder seeking", "seed round"],
      location: DC,
      attributes: { synthetic: true, role: "investor", ticketSize: 250000, stage: "seed", currency: "USD" },
      metadata: meta("capital", "DEMO synthetic fund"),
      trust: trust("stub", "synthetic fund"),
      provenance: "synthetic",
    }),
    base({
      id: "founder-seeking-250k",
      type: "human",
      name: "Rafi is raising",
      description: "DEMO synthetic founder seeking a $250k check in DC. Not a real company.",
      offers: ["seed round", "DC startup"],
      seeks: ["invests", "writes $250k checks", "capital", "need a check", "looking for an investor"],
      location: DC,
      attributes: { synthetic: true, role: "founder", ticketSize: 250000, stage: "seed", currency: "USD" },
      metadata: meta("capital", "DEMO synthetic founder"),
      trust: trust("stub", "synthetic founder"),
      provenance: "synthetic",
    }),
    base({
      id: "founder-needs-intro",
      type: "human",
      name: "Sable needs an introduction",
      description: "DEMO synthetic founder looking for an introduction to an investor. Not real.",
      offers: ["warm story", "seed round"],
      seeks: ["introduction to an investor", "need an introduction", "capital"],
      location: DC,
      attributes: { synthetic: true, role: "founder", ticketSize: 250000, stage: "pre-seed", currency: "USD" },
      metadata: meta("capital", "DEMO synthetic founder"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "founder-nyc",
      type: "human",
      name: "NYC founder seeking",
      description: "DEMO synthetic NYC founder seeking capital. Geo contrast. Not real.",
      offers: ["seed round"],
      seeks: ["invests", "looking for an investor", "capital"],
      location: NYC,
      attributes: { synthetic: true, role: "founder", ticketSize: 250000, stage: "seed", currency: "USD" },
      metadata: meta("capital", "DEMO synthetic founder"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
  ];
}

function travel(): Entity[] {
  return [
    base({
      id: "stay-berlin-tonight",
      type: "resource",
      name: "Mitte room tonight",
      description:
        "DEMO synthetic stay in Berlin — room tonight. Reuses listing/seeker + rent, not a hotel engine. Not a real room.",
      offers: ["stay in Berlin", "room tonight", "accommodation", "hotel-like room", "going to Berlin"],
      seeks: ["guest going to Berlin", "someone who needs a room tonight"],
      location: BERLIN,
      availability: "tonight",
      attributes: {
        synthetic: true,
        role: "listing",
        listingKind: "stay",
        rent: 78,
        currency: "EUR",
        durationNights: 1,
        availableFrom: TODAY,
        neighborhood: "Mitte",
      },
      metadata: meta("travel", "DEMO synthetic stay"),
      trust: trust("stub", "synthetic stay — not a booking"),
      provenance: "synthetic",
    }),
    base({
      id: "stay-hostel-berlin",
      type: "resource",
      name: "Kreuzberg hostel bed",
      description: "DEMO synthetic hostel in Berlin. Same listing role as apartments. Not real.",
      offers: ["hostel", "stay in Berlin", "accommodation", "room tonight", "going to Berlin"],
      seeks: ["traveler going to Berlin"],
      location: BERLIN,
      availability: "tonight",
      attributes: {
        synthetic: true,
        role: "listing",
        listingKind: "hostel",
        rent: 32,
        currency: "EUR",
        durationNights: 1,
        availableFrom: TODAY,
      },
      metadata: meta("travel", "DEMO synthetic stay"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "stay-hotel-berlin",
      type: "resource",
      name: "Alexanderplatz hotel night",
      description: "DEMO synthetic hotel stay in Berlin. Not a real hotel.",
      offers: ["hotel", "stay in Berlin", "accommodation", "going to Berlin"],
      seeks: ["guest"],
      location: BERLIN,
      attributes: {
        synthetic: true,
        role: "listing",
        listingKind: "hotel",
        rent: 140,
        currency: "EUR",
        durationNights: 1,
        availableFrom: TODAY,
      },
      metadata: meta("travel", "DEMO synthetic stay"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "stay-dc-tonight",
      type: "resource",
      name: "Georgetown room tonight",
      description:
        "DEMO synthetic DC room tonight. Overlaps apartment Georgetown listings on purpose — same role, nights not months.",
      offers: ["room tonight", "stay in Washington", "accommodation", "room in Georgetown"],
      seeks: ["guest who needs a room tonight"],
      location: DC,
      availability: "tonight",
      attributes: {
        synthetic: true,
        role: "listing",
        listingKind: "stay",
        rent: 95,
        currency: "USD",
        durationNights: 1,
        availableFrom: TODAY,
        neighborhood: "Georgetown",
      },
      metadata: meta("travel", "DEMO synthetic stay"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "seeker-berlin-tonight",
      type: "human",
      name: "Going to Berlin tonight",
      description: "DEMO synthetic traveler who needs a room tonight in Berlin. Not a real person.",
      offers: ["one-night stay", "pays tonight"],
      seeks: ["stay in Berlin", "room tonight", "accommodation", "hostel", "going to Berlin"],
      location: BERLIN,
      attributes: {
        synthetic: true,
        role: "seeker",
        listingKind: "stay",
        budget: 80,
        currency: "EUR",
        durationNights: 1,
        availableFrom: TODAY,
      },
      metadata: meta("travel", "DEMO synthetic traveler"),
      trust: trust("stub", "synthetic traveler"),
      provenance: "synthetic",
    }),
    base({
      id: "seeker-going-to-berlin",
      type: "human",
      name: "Sam is going to Berlin",
      description: "DEMO synthetic person going to Berlin who needs accommodation. Not real.",
      offers: ["flexible dates"],
      seeks: ["stay in Berlin", "going to Berlin", "hotel", "accommodation"],
      location: DC,
      attributes: { synthetic: true, role: "seeker", listingKind: "stay", budget: 120, currency: "EUR" },
      metadata: meta("travel", "DEMO synthetic traveler"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "seeker-dc-tonight",
      type: "human",
      name: "Needs a DC room tonight",
      description: "DEMO synthetic person who needs a room tonight in Washington. Not real.",
      offers: ["pays cash tonight"],
      seeks: ["room tonight", "stay in Washington", "accommodation"],
      location: DC,
      attributes: {
        synthetic: true,
        role: "seeker",
        listingKind: "stay",
        budget: 100,
        currency: "USD",
        availableFrom: TODAY,
      },
      metadata: meta("travel", "DEMO synthetic traveler"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
  ];
}

function events(): Entity[] {
  return [
    base({
      id: "event-dc-builders",
      type: "resource",
      name: "DC Builders Night",
      description: "DEMO synthetic event in Washington. Shared context, not a ticket vendor. Not a real meetup.",
      offers: ["attending", "event in DC", "meetup", "conference-like night", "from my city"],
      seeks: ["attendees from my city", "speakers"],
      location: DC,
      attributes: { synthetic: true, role: "event", when: "Saturday", cityContext: "Washington" },
      metadata: meta("events", "DEMO synthetic event"),
      trust: trust("stub", "synthetic event"),
      provenance: "synthetic",
    }),
    base({
      id: "event-berlin-salon",
      type: "resource",
      name: "Berlin Voice Salon",
      description: "DEMO synthetic Berlin event. Not a real salon.",
      offers: ["attending", "meetup", "speaking slots", "event in Berlin"],
      seeks: ["attendees", "speakers"],
      location: BERLIN,
      attributes: { synthetic: true, role: "event", when: "next week" },
      metadata: meta("events", "DEMO synthetic event"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "speaker-dc",
      type: "human",
      name: "Nico is speaking",
      description: "DEMO synthetic speaker at DC Builders Night. Not a real person.",
      offers: ["speaking at DC Builders Night", "speaking", "attending"],
      seeks: ["people attending from my city"],
      location: DC,
      attributes: { synthetic: true, role: "speaker", eventId: "event-dc-builders" },
      metadata: meta("events", "DEMO synthetic speaker"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "speaker-ai",
      type: "ai",
      name: "EmceeBot",
      description: "This is an AI. It is not a human. DEMO speaker/emcee for events.",
      offers: ["speaking at", "emcee", "attending"],
      seeks: ["events that want an AI host"],
      attributes: { synthetic: true, role: "speaker" },
      metadata: {
        ...meta("events", "DEMO synthetic AI speaker"),
        aiDisclosure: "This is an AI. It is not a human.",
        isAI: true,
      },
      trust: trust("stub", "AI speaker stub"),
      provenance: "ai_generated",
    }),
    base({
      id: "attendee-dc",
      type: "human",
      name: "Riley is attending",
      description: "DEMO synthetic attendee from Washington. Wants to meet people from my city. Not real.",
      offers: ["attending", "from my city"],
      seeks: ["event in DC", "meetup", "people attending from my city", "speaking at"],
      location: DC,
      attributes: { synthetic: true, role: "attendee", eventId: "event-dc-builders" },
      metadata: meta("events", "DEMO synthetic attendee"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "attendee-berlin-in-dc",
      type: "human",
      name: "Lina (Berlin, in DC this week)",
      description: "DEMO synthetic visitor attending DC events, not from my city. Contrast card. Not real.",
      offers: ["attending"],
      seeks: ["meetup", "event in DC"],
      location: BERLIN,
      attributes: { synthetic: true, role: "attendee" },
      metadata: meta("events", "DEMO synthetic attendee"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "community-builders",
      type: "community",
      name: "WhoElse Builders (community)",
      description:
        "DEMO synthetic community. Offers help understanding this market and shared event context. Not a real org.",
      offers: [
        "help understanding this market",
        "community",
        "attending",
        "from my city",
        "understand this market",
      ],
      seeks: ["members", "speakers"],
      location: DC,
      attributes: { synthetic: true, role: "event", kind: "community" },
      metadata: meta("events", "DEMO synthetic community"),
      trust: trust("stub", "synthetic community"),
      provenance: "synthetic",
    }),
  ];
}

function childcare(): Entity[] {
  return [
    base({
      id: "caregiver-tonight-dc",
      type: "human",
      name: "Priya can babysit tonight",
      description: "DEMO synthetic verified-stub caregiver nearby. Safety is evidence, not a score. Not a real sitter.",
      offers: ["babysit tonight", "childcare", "babysitter", "nearby"],
      seeks: ["parent who needs childcare tonight"],
      location: DC,
      availability: "tonight",
      attributes: { synthetic: true, role: "caregiver", when: "tonight", rate: 25, currency: "USD" },
      metadata: meta("childcare", "DEMO synthetic caregiver"),
      trust: trust("evidence", "background-check stub — not a real credential", {
        verified: true,
        verifiedBy: "demo-safety-stub",
        references: ["neighbor-stub"],
        outcomes: [{ label: "sat for two kids", result: "stub" }],
      }),
      provenance: "synthetic",
    }),
    base({
      id: "caregiver-unverified",
      type: "human",
      name: "Cash-only sitter (unverified)",
      description: "DEMO synthetic unverified cheaper caregiver — trust contrast, not a recommendation. Not real.",
      offers: ["babysit tonight", "childcare", "babysitter"],
      seeks: ["parent"],
      location: DC,
      attributes: { synthetic: true, role: "caregiver", when: "tonight", rate: 12, currency: "USD" },
      metadata: meta("childcare", "DEMO synthetic caregiver"),
      trust: trust("stub", "unverified — contrast card"),
      provenance: "synthetic",
    }),
    base({
      id: "caregiver-reciprocal",
      type: "human",
      name: "Jordan (reciprocal childcare)",
      description: "DEMO synthetic parent/caregiver who babysits and also needs childcare. Reciprocal. Not real.",
      offers: ["babysit tonight", "childcare swap", "babysitter"],
      seeks: ["needs childcare", "backup sitter nearby"],
      location: DC,
      attributes: { synthetic: true, role: "caregiver", when: "tonight", rate: 0, currency: "USD" },
      metadata: meta("childcare", "DEMO synthetic caregiver"),
      trust: trust("evidence", "swap stub", { references: ["swap-circle-stub"] }),
      provenance: "synthetic",
    }),
    base({
      id: "parent-needs-tonight",
      type: "human",
      name: "Needs childcare tonight",
      description: "DEMO synthetic parent who needs childcare tonight nearby. Not a real family.",
      offers: ["pay tonight", "references"],
      seeks: ["babysit tonight", "childcare", "babysitter", "nearby"],
      location: DC,
      attributes: { synthetic: true, role: "parent", when: "tonight", rate: 28, currency: "USD" },
      metadata: meta("childcare", "DEMO synthetic parent"),
      trust: trust("stub", "synthetic parent"),
      provenance: "synthetic",
    }),
    base({
      id: "parent-nearby",
      type: "human",
      name: "Foggy Bottom parent",
      description: "DEMO synthetic parent nearby who needs a babysitter. Not real.",
      offers: ["short notice pay"],
      seeks: ["babysitter", "childcare", "nearby"],
      location: DC,
      attributes: { synthetic: true, role: "parent", when: "tonight", rate: 22, currency: "USD" },
      metadata: meta("childcare", "DEMO synthetic parent"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "ai-sitter-match",
      type: "ai",
      name: "SitterIndex",
      description: "This is an AI. It is not a human. DEMO matcher that helps find childcare — not a babysitter.",
      offers: ["childcare matching", "who else can babysit"],
      seeks: ["parents who need childcare"],
      attributes: { synthetic: true, role: "caregiver", when: "tonight" },
      metadata: {
        ...meta("childcare", "DEMO synthetic AI"),
        aiDisclosure: "This is an AI. It is not a human. It does not babysit.",
        isAI: true,
      },
      trust: trust("stub", "AI matcher — not a caregiver"),
      provenance: "ai_generated",
    }),
  ];
}

function collab(): Entity[] {
  return [
    base({
      id: "collab-designer",
      type: "human",
      name: "Cleo designs (seeks a writer)",
      description: "DEMO synthetic designer who wants a complementary writer to join this project. Not real.",
      offers: ["design", "complementary design", "join this project", "creative collab", "design partner"],
      seeks: ["writer", "complementary writer", "write together", "join this project"],
      location: DC,
      attributes: { synthetic: true, craft: "design" },
      metadata: meta("collab", "DEMO synthetic collaborator"),
      trust: trust("evidence", "portfolio stub", { portfolio: ["https://example.invalid/cleo"] }),
      provenance: "synthetic",
    }),
    base({
      id: "collab-writer",
      type: "human",
      name: "Bo writes (seeks a designer)",
      description: "DEMO complementary writer who wants to join this project with a designer. Not real.",
      offers: ["write together", "writer", "complementary", "join this project", "creative collab"],
      seeks: ["design partner", "design", "complementary design", "join this project"],
      location: DC,
      attributes: { synthetic: true, craft: "write" },
      metadata: meta("collab", "DEMO synthetic collaborator"),
      trust: trust("stub", "synthetic writer"),
      provenance: "synthetic",
    }),
    base({
      id: "collab-project",
      type: "resource",
      name: "Zine project (needs both)",
      description: "DEMO multi-party project seeking a designer and a writer. Not a real zine.",
      offers: ["join this project", "creative collab", "shared credit"],
      seeks: ["design partner", "write together", "complementary", "designer", "writer"],
      location: DC,
      attributes: { synthetic: true, craft: "project" },
      metadata: meta("collab", "DEMO synthetic project"),
      trust: trust("stub", "synthetic project"),
      provenance: "synthetic",
    }),
    base({
      id: "collab-illustrator",
      type: "human",
      name: "Pax illustrates",
      description: "DEMO complementary illustrator open to join this project. Not real.",
      offers: ["illustrate", "complementary", "join this project", "creative collab"],
      seeks: ["writer", "design partner", "join this project"],
      location: DC,
      attributes: { synthetic: true, craft: "illustrate" },
      metadata: meta("collab", "DEMO synthetic collaborator"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "collab-ai-muse",
      type: "ai",
      name: "CollabMuse",
      description: "This is an AI. It is not a human. DEMO complementary drafting partner for a project.",
      offers: ["write together", "complementary", "join this project", "creative collab"],
      seeks: ["humans who want a drafting partner"],
      attributes: { synthetic: true, craft: "write" },
      metadata: {
        ...meta("collab", "DEMO synthetic AI collaborator"),
        aiDisclosure: "This is an AI. It is not a human.",
        isAI: true,
      },
      trust: trust("stub", "AI collaborator"),
      provenance: "ai_generated",
    }),
  ];
}

function compute(): Entity[] {
  return [
    base({
      id: "compute-gpu-dc",
      type: "resource",
      name: "Dupont GPU host",
      description: "DEMO synthetic GPU host in DC. Capacity + latency as attributes. Not real hardware.",
      offers: ["host GPU", "GPU", "compute capacity", "cheaper GPU", "inference host"],
      seeks: ["workload that needs a GPU", "jobs that seek GPU"],
      location: DC,
      attributes: {
        synthetic: true,
        role: "compute",
        gpu: true,
        price: 1.2,
        currency: "USD",
        latencyMs: 40,
        capacity: 4,
        state: "available",
      },
      metadata: meta("compute", "DEMO synthetic compute"),
      trust: trust("stub", "synthetic GPU"),
      provenance: "synthetic",
    }),
    base({
      id: "compute-cheap-slow",
      type: "resource",
      name: "Thrift GPU (cheap, high latency)",
      description: "DEMO cheaper GPU with worse latency. State + price tradeoff. Not real.",
      offers: ["cheaper GPU", "cheaper compute", "GPU", "host GPU"],
      seeks: ["batch workload"],
      location: DC,
      attributes: {
        synthetic: true,
        role: "compute",
        gpu: true,
        price: 0.3,
        currency: "USD",
        latencyMs: 400,
        capacity: 1,
        state: "available",
      },
      metadata: meta("compute", "DEMO synthetic compute"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "compute-busy",
      type: "resource",
      name: "Shaw GPU (busy)",
      description: "DEMO busy GPU host — state changed. Not real.",
      offers: ["GPU", "host GPU", "compute capacity"],
      seeks: ["later jobs"],
      location: DC,
      attributes: {
        synthetic: true,
        role: "compute",
        gpu: true,
        price: 0.9,
        currency: "USD",
        latencyMs: 25,
        capacity: 0,
        state: "busy",
      },
      metadata: meta("compute", "DEMO synthetic compute"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "workload-needs-gpu",
      type: "resource",
      name: "Inference job (needs GPU)",
      description: "DEMO synthetic workload that needs cheaper GPU capacity. Not a real job.",
      offers: ["inference job", "pays for capacity"],
      seeks: ["host GPU", "GPU", "cheaper GPU", "compute capacity"],
      location: DC,
      attributes: { synthetic: true, role: "workload", gpu: true, price: 1.0, currency: "USD", latencyMs: 80 },
      metadata: meta("compute", "DEMO synthetic workload"),
      trust: trust("stub", "synthetic workload"),
      provenance: "synthetic",
    }),
    base({
      id: "agent-gpu-router",
      type: "agent",
      name: "LaneRouter",
      description: "DEMO synthetic agent that routes work to a cheaper GPU host via whoelse.find.",
      offers: ["agent routing", "host GPU routing", "cheaper compute", "GPU"],
      seeks: ["available GPU hosts"],
      attributes: {
        synthetic: true,
        role: "compute",
        gpu: true,
        price: 0.15,
        priceUsd: 0.15,
        latencyMs: 12,
        apiEndpoint: "/api/agents/agent-gpu-router/invoke",
        mcpEndpoint: "/api/mcp",
        authRequirements: { demo: true },
        fallbackTo: ["compute-cheap-slow"],
      },
      metadata: {
        ...meta("compute", "DEMO synthetic agent"),
        aiDisclosure: "This is an AI agent. It is not a human.",
        isAI: true,
      },
      trust: trust("stub", "routing stub"),
      provenance: "ai_generated",
    }),
    base({
      id: "compute-berlin",
      type: "resource",
      name: "Mitte GPU",
      description: "DEMO synthetic Berlin GPU host. Geo contrast. Not real.",
      offers: ["host GPU", "GPU", "compute capacity"],
      seeks: ["EU workloads"],
      location: BERLIN,
      attributes: {
        synthetic: true,
        role: "compute",
        gpu: true,
        price: 1.1,
        currency: "EUR",
        latencyMs: 35,
        state: "available",
      },
      metadata: meta("compute", "DEMO synthetic compute"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
  ];
}

function data(): Entity[] {
  return [
    base({
      id: "dataset-market-dc",
      type: "dataset",
      name: "DC market dataset",
      description:
        "DEMO synthetic dataset. Offers help understanding this market via original rows. Ownership stub. Not real data.",
      offers: [
        "dataset",
        "help understanding this market",
        "understand this market",
        "original source",
        "data provenance",
      ],
      seeks: ["researcher", "someone who needs to verify this claim"],
      location: DC,
      attributes: { synthetic: true, role: "publisher", access: "demo", owner: "dataset-market-dc" },
      metadata: meta("data", "DEMO synthetic dataset"),
      trust: trust("evidence", "provenance stub", {
        verified: true,
        verifiedBy: "demo-source-stub",
        outcomes: [{ label: "original rows", result: "synthetic" }],
      }),
      provenance: "synthetic",
    }),
    base({
      id: "dataset-claims",
      type: "dataset",
      name: "Claim Ledger (original source)",
      description: "DEMO synthetic original source for claims. Who else can verify this claim? Not real.",
      offers: ["original source", "dataset", "verify this claim", "data provenance"],
      seeks: ["unverified claims"],
      attributes: { synthetic: true, role: "publisher", access: "demo" },
      metadata: meta("data", "DEMO synthetic dataset"),
      trust: trust("evidence", "original-source stub", { verified: true, verifiedBy: "publisher-stub" }),
      provenance: "synthetic",
    }),
    base({
      id: "report-market",
      type: "resource",
      name: "WhoElse market report",
      description: "DEMO synthetic report. Help understanding this market. Not a real publication.",
      offers: ["help understanding this market", "understand this market", "report", "original source"],
      seeks: ["readers who need a briefing"],
      location: DC,
      attributes: { synthetic: true, role: "publisher", kind: "report" },
      metadata: meta("data", "DEMO synthetic report"),
      trust: trust("stub", "synthetic report"),
      provenance: "synthetic",
    }),
    base({
      id: "researcher-verify-claim",
      type: "human",
      name: "Ira verifies claims",
      description: "DEMO synthetic researcher who wants a dataset to verify this claim. Not real.",
      offers: ["attention", "cite the source"],
      seeks: ["dataset", "original source", "verify this claim", "data provenance"],
      location: DC,
      attributes: { synthetic: true, role: "researcher" },
      metadata: meta("data", "DEMO synthetic researcher"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "ai-source-checker",
      type: "ai",
      name: "SourcePin",
      description: "This is an AI. It is not a human. DEMO agent that traces an original source to verify this claim.",
      offers: ["verify this claim", "original source", "data provenance"],
      seeks: ["claims to check"],
      attributes: { synthetic: true, role: "publisher" },
      metadata: {
        ...meta("data", "DEMO synthetic AI"),
        aiDisclosure: "This is an AI. It is not a human.",
        isAI: true,
      },
      trust: trust("stub", "AI provenance helper"),
      provenance: "ai_generated",
    }),
    base({
      id: "publisher-civic",
      type: "company",
      name: "Civic Facts Desk",
      description: "DEMO synthetic publisher that owns a dataset. Access/ownership stub. Not real.",
      offers: ["dataset", "original source", "help understanding this market"],
      seeks: ["licensed researchers"],
      location: DC,
      attributes: { synthetic: true, role: "publisher", access: "licensed-stub", owner: "publisher-civic" },
      metadata: meta("data", "DEMO synthetic publisher"),
      trust: trust("stub", "ownership stub"),
      provenance: "synthetic",
    }),
  ];
}

function local(): Entity[] {
  return [
    base({
      id: "shop-open-now-dc",
      type: "company",
      name: "Shaw Bodega (open now)",
      description: "DEMO synthetic shop open now that sells nearby and can deliver today. Not a real store.",
      offers: ["sells nearby", "open now", "deliver today", "local shop", "local commerce"],
      seeks: ["buyer nearby"],
      location: DC,
      availability: "open now",
      attributes: {
        synthetic: true,
        role: "seller",
        openNow: true,
        deliverToday: true,
        price: 8,
        currency: "USD",
        state: "open",
      },
      metadata: meta("local", "DEMO synthetic shop"),
      trust: trust("stub", "synthetic shop"),
      provenance: "synthetic",
    }),
    base({
      id: "shop-closed-dc",
      type: "company",
      name: "Dupont Counter (closed)",
      description: "DEMO closed shop — real-time state. Not real.",
      offers: ["sells nearby", "local shop"],
      seeks: ["tomorrow's buyers"],
      location: DC,
      attributes: {
        synthetic: true,
        role: "seller",
        openNow: false,
        deliverToday: false,
        price: 9,
        currency: "USD",
        state: "closed",
      },
      metadata: meta("local", "DEMO synthetic shop"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "shop-deliver-today",
      type: "company",
      name: "Adams Deliveries",
      description: "DEMO synthetic shop that can deliver today nearby. Not real.",
      offers: ["deliver today", "sells nearby", "open now", "local store"],
      seeks: ["buyer who needs deliver today"],
      location: DC,
      attributes: {
        synthetic: true,
        role: "seller",
        openNow: true,
        deliverToday: true,
        price: 12,
        currency: "USD",
        state: "open",
      },
      metadata: meta("local", "DEMO synthetic shop"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "buyer-nearby-local",
      type: "human",
      name: "Needs something nearby now",
      description: "DEMO synthetic buyer who wants a shop open now that can deliver today. Not real.",
      offers: ["pickup or delivery"],
      seeks: ["open now", "deliver today", "sells nearby", "local shop"],
      location: DC,
      attributes: { synthetic: true, role: "buyer", openNow: true, deliverToday: true },
      metadata: meta("local", "DEMO synthetic buyer"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "shop-berlin-open",
      type: "company",
      name: "Späti Mitte (open now)",
      description: "DEMO synthetic Berlin shop open now. Geo contrast. Not real.",
      offers: ["open now", "sells nearby", "local shop"],
      seeks: ["nearby buyer"],
      location: BERLIN,
      attributes: { synthetic: true, role: "seller", openNow: true, deliverToday: false, state: "open", price: 4 },
      metadata: meta("local", "DEMO synthetic shop"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
    base({
      id: "local-hardware-overlap",
      type: "company",
      name: "U Street Hardware (open now)",
      description: "DEMO overlap with products — sells nearby drills, open now. Same seller role. Not real.",
      offers: ["sells nearby", "open now", "drill", "this product", "local commerce"],
      seeks: ["buyer nearby"],
      location: DC,
      attributes: {
        synthetic: true,
        role: "seller",
        kind: "drill",
        openNow: true,
        deliverToday: true,
        inStock: true,
        price: 36,
        currency: "USD",
        state: "open",
      },
      metadata: meta("local", "DEMO synthetic shop"),
      trust: trust("stub", "synthetic"),
      provenance: "synthetic",
    }),
  ];
}

function metaMarket(): Entity[] {
  return [
    base({
      id: "community-market-watchers",
      type: "community",
      name: "Market Watchers circle",
      description:
        "DEMO synthetic community for people who need help understanding this market. Not a real group.",
      offers: ["help understanding this market", "understand this market", "community", "shared notes"],
      seeks: ["members who have questions about this market"],
      location: DC,
      attributes: { synthetic: true, role: "event", kind: "community" },
      metadata: meta("experts", "DEMO synthetic community"),
      trust: trust("stub", "synthetic community"),
      provenance: "synthetic",
    }),
  ];
}
